version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres       # замените на свои данные
      POSTGRES_PASSWORD: FcEnP0H4+  # замените на свои данные
      POSTGRES_DB: money_flow             # замените на свою базу данных
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      # Передайте переменные окружения через файл или прямо здесь.
      DATABASE_URL: postgresql://your_user:your_password@postgres:5432/your_db
      SECRET_KEY: your_secret_key        # замените на свой секретный ключ
      ALGORITHM: HS256                     # или другой алгоритм по необходимости
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE_URL: http://localhost:8000  # или http://backend:8000, если использовать внутри сети Docker
    depends_on:
      - backend

volumes:
  postgres_data:
