version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ghbdtnjvktn+
      POSTGRES_DB: money_flow_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      # Передайте переменные окружения через файл или прямо здесь.
      DATABASE_URL: postgresql://postgres:Ghbdtnjvktn@postgres:5432/money_flow_db
      SECRET_KEY: your_secret_key
      ALGORITHM: HS256 
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      VITE_API_BASE_URL: http://localhost:8001 
    depends_on:
      - backend

volumes:
  postgres_data:
