version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ghbdtnjvktn
      POSTGRES_DB: money_flow_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      # Передайте переменные окружения через файл или прямо здесь.
      DATABASE_URL: postgresql://postgres:Ghbdtnjvktn@postgres:5432/money_flow_db
      SECRET_KEY: 15b07f9af1e3f85afc6cd40ea4d6471b427ebe796d65ae2c043b23dae3a71c82
      ALGORITHM: HS256 
    depends_on:
      - postgres

  frontend:
    container_name: money_flow_frontend
    # Теперь мы собираем образ из Dockerfile, который создали в папке frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      # Nginx внутри контейнера слушает порт 80.
      # Мы по-прежнему пробрасываем его на порт 3000 хоста,
      # чтобы ваш основной Nginx на сервере мог с ним связаться.
      - "3000:80"
    depends_on:
      - backend
    networks:
      - money_flow_network
    restart: unless-stopped

volumes:
  postgres_data:
