"""Make type column in BudgetItem nullable and add default

Revision ID: 01ebee5f7e33
Revises: 72969885258b
Create Date: 2025-07-08 11:10:53.425955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01ebee5f7e33'
down_revision: Union[str, None] = '72969885258b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_items', sa.Column('type', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budget_items', 'type')
    # ### end Alembic commands ###
