"""Resolve remaining ambiguous foreign key for Workspace.owner

Revision ID: 0f385b2c3719
Revises: 31c23b4f741f
Create Date: 2025-06-21 23:15:11.603835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f385b2c3719'
down_revision: Union[str, None] = '31c23b4f741f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
