"""Initial database schema from scratch

Revision ID: 169bfe94363d
Revises:
Create Date: 2025-07-15 13:19:10.966200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '169bfe94363d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Сначала создаем таблицы, от которых ничего не зависит.
    op.create_table('account_types',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('code', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_account_types')),
        sa.UniqueConstraint('code', name=op.f('uq_account_types_code')),
        sa.UniqueConstraint('name', name=op.f('uq_account_types_name'))
    )
    op.create_index(op.f('ix_account_types_id'), 'account_types', ['id'], unique=False)

    op.create_table('roles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)

    # 2. Теперь создаем таблицу 'users'. Мы временно не можем создать ее зависимость
    # от 'workspaces', так как у них циклическая зависимость.
    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('full_name', sa.String(), nullable=True),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('username', sa.String(), nullable=True),
        sa.Column('password_hash', sa.String(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('is_superuser', sa.Boolean(), nullable=True),
        sa.Column('role_id', sa.Integer(), nullable=True),
        sa.Column('active_workspace_id', sa.Integer(), nullable=True),
        # ВАЖНО: Связь с `workspaces` будет добавлена позже, чтобы разорвать цикл.
        sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)

    # 3. Теперь создаем 'workspaces', которые ссылаются на уже существующую таблицу 'users'.
    op.create_table('workspaces',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('owner_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_workspaces_owner_id_users')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces'))
    )
    op.create_index(op.f('ix_workspaces_id'), 'workspaces', ['id'], unique=False)
    op.create_index(op.f('ix_workspaces_name'), 'workspaces', ['name'], unique=False)

    # 4. Теперь, когда обе таблицы существуют, добавляем недостающую связь от 'users' к 'workspaces'.
    op.create_foreign_key(
        op.f('fk_users_active_workspace_id_workspaces'),
        'users', 'workspaces',
        ['active_workspace_id'], ['id']
    )

    # 5. Создаем все остальные таблицы, которые зависят от `users` и `workspaces`.
    op.create_table('accounts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('currency', sa.String(length=3), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('account_type_id', sa.Integer(), nullable=False),
        sa.Column('owner_id', sa.Integer(), nullable=True),
        sa.Column('workspace_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['account_type_id'], ['account_types.id'], name=op.f('fk_accounts_account_type_id_account_types')),
        sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_accounts_owner_id_users')),
        sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_accounts_workspace_id_workspaces')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts'))
    )
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_index(op.f('ix_accounts_name'), 'accounts', ['name'], unique=False)
    
    op.create_table('budgets',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('start_date', sa.Date(), nullable=False),
        sa.Column('end_date', sa.Date(), nullable=False),
        sa.Column('owner_id', sa.Integer(), nullable=False),
        sa.Column('workspace_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_budgets_owner_id_users')),
        sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_budgets_workspace_id_workspaces')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_budgets')),
        sa.UniqueConstraint('name', 'workspace_id', 'start_date', 'end_date', name='_budget_name_workspace_period_uc')
    )
    op.create_index(op.f('ix_budgets_id'), 'budgets', ['id'], unique=False)

    op.create_table('counterparties',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True, comment='Название контрагента'),
        sa.Column('type', sa.Enum('CLIENT', 'SUPPLIER', 'EMPLOYEE', 'OTHER', name='counterpartytype'), nullable=False),
        sa.Column('inn', sa.String(), nullable=True, comment='ИНН'),
        sa.Column('contact_person', sa.String(), nullable=True, comment='Контактное лицо'),
        sa.Column('contact_info', sa.String(), nullable=True, comment='Контакты (телефон, email)'),
        sa.Column('owner_id', sa.Integer(), nullable=False),
        sa.Column('workspace_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_counterparties_owner_id_users'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_counterparties_workspace_id_workspaces'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_counterparties')),
        sa.UniqueConstraint('inn', name=op.f('uq_counterparties_inn'))
    )
    op.create_index(op.f('ix_counterparties_id'), 'counterparties', ['id'], unique=False)
    op.create_index(op.f('ix_counterparties_name'), 'counterparties', ['name'], unique=True)
    
    op.create_table('dds_articles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('article_type', sa.String(), nullable=False),
        sa.Column('parent_id', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('workspace_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['parent_id'], ['dds_articles.id'], name=op.f('fk_dds_articles_parent_id_dds_articles')),
        sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_dds_articles_workspace_id_workspaces')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_dds_articles')),
        sa.UniqueConstraint('name', 'workspace_id', name='_dds_article_name_workspace_uc')
    )
    op.create_index(op.f('ix_dds_articles_id'), 'dds_articles', ['id'], unique=False)
    op.create_index(op.f('ix_dds_articles_name'), 'dds_articles', ['name'], unique=False)
    
    op.create_table('planned_payments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('description', sa.String(), nullable=False, comment='Описание платежа'),
        sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Сумма платежа (всегда положительная)'),
        sa.Column('payment_date', sa.Date(), nullable=False, comment='Планируемая дата'),
        sa.Column('payment_type', sa.Enum('INCOME', 'EXPENSE', name='paymenttype'), nullable=False, comment='Тип: доход или расход'),
        sa.Column('is_recurring', sa.Boolean(), nullable=False),
        sa.Column('recurrence_rule', sa.String(), nullable=True, comment='Правило повторения (напр., RRULE)'),
        sa.Column('workspace_id', sa.Integer(), nullable=False),
        sa.Column('owner_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_planned_payments_owner_id_users'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_planned_payments_workspace_id_workspaces'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_planned_payments'))
    )
    op.create_index(op.f('ix_planned_payments_payment_date'), 'planned_payments', ['payment_date'], unique=False)
    
    op.create_table('budget_items',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('budgeted_amount', sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column('type', sa.String(length=10), nullable=True),
        sa.Column('budget_id', sa.Integer(), nullable=False),
        sa.Column('dds_article_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint('budgeted_amount > 0', name=op.f('ck_budget_items_check_budget_item_amount_positive')),
        sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], name=op.f('fk_budget_items_budget_id_budgets')),
        sa.ForeignKeyConstraint(['dds_article_id'], ['dds_articles.id'], name=op.f('fk_budget_items_dds_article_id_dds_articles')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_budget_items'))
    )
    op.create_index(op.f('ix_budget_items_id'), 'budget_items', ['id'], unique=False)
    
    op.create_table('contracts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False, comment='Название договора/проекта'),
        sa.Column('description', sa.Text(), nullable=True, comment='Описание договора/проекта'),
        sa.Column('start_date', sa.Date(), nullable=False, comment='Дата начала договора'),
        sa.Column('end_date', sa.Date(), nullable=True, comment='Дата окончания договора'),
        sa.Column('value', sa.Float(), nullable=True, comment='Сумма договора'),
        sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'ARCHIVED', 'PENDING', name='contractstatus'), nullable=False, comment='Статус договора'),
        sa.Column('counterparty_id', sa.Integer(), nullable=False),
        sa.Column('workspace_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], name=op.f('fk_contracts_counterparty_id_counterparties'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_contracts_workspace_id_workspaces'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_contracts'))
    )
    op.create_index(op.f('ix_contracts_counterparty_id'), 'contracts', ['counterparty_id'], unique=False)
    op.create_index(op.f('ix_contracts_id'), 'contracts', ['id'], unique=False)
    op.create_index(op.f('ix_contracts_name'), 'contracts', ['name'], unique=False)
    op.create_index(op.f('ix_contracts_workspace_id'), 'contracts', ['workspace_id'], unique=False)
    
    op.create_table('mapping_rules',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('keyword', sa.String(), nullable=False),
        sa.Column('dds_article_id', sa.Integer(), nullable=True),
        sa.Column('workspace_id', sa.Integer(), nullable=False),
        sa.Column('owner_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['dds_article_id'], ['dds_articles.id'], name=op.f('fk_mapping_rules_dds_article_id_dds_articles')),
        sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_mapping_rules_owner_id_users')),
        sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_mapping_rules_workspace_id_workspaces')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_mapping_rules')),
        sa.UniqueConstraint('keyword', 'workspace_id', name='_keyword_workspace_uc')
    )
    op.create_index(op.f('ix_mapping_rules_id'), 'mapping_rules', ['id'], unique=False)
    op.create_index(op.f('ix_mapping_rules_keyword'), 'mapping_rules', ['keyword'], unique=False)
    
    op.create_table('transactions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('transaction_date', sa.Date(), nullable=False),
        sa.Column('transaction_type', sa.Enum('INCOME', 'EXPENSE', 'TRANSFER', name='transactiontype'), nullable=False),
        sa.Column('from_account_id', sa.Integer(), nullable=True),
        sa.Column('to_account_id', sa.Integer(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('workspace_id', sa.Integer(), nullable=False),
        sa.Column('dds_article_id', sa.Integer(), nullable=True),
        sa.Column('counterparty_id', sa.Integer(), nullable=True),
        sa.Column('contract_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint('amount > 0', name=op.f('ck_transactions_check_transaction_amount_positive')),
        sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], name=op.f('fk_transactions_contract_id_contracts'), ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], name=op.f('fk_transactions_counterparty_id_counterparties')),
        sa.ForeignKeyConstraint(['dds_article_id'], ['dds_articles.id'], name=op.f('fk_transactions_dds_article_id_dds_articles')),
        sa.ForeignKeyConstraint(['from_account_id'], ['accounts.id'], name=op.f('fk_transactions_from_account_id_accounts')),
        sa.ForeignKeyConstraint(['to_account_id'], ['accounts.id'], name=op.f('fk_transactions_to_account_id_accounts')),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_transactions_user_id_users'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_transactions_workspace_id_workspaces'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    op.create_index(op.f('ix_transactions_contract_id'), 'transactions', ['contract_id'], unique=False)
    op.create_index(op.f('ix_transactions_counterparty_id'), 'transactions', ['counterparty_id'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_transaction_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_counterparty_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_contract_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_mapping_rules_keyword'), table_name='mapping_rules')
    op.drop_index(op.f('ix_mapping_rules_id'), table_name='mapping_rules')
    op.drop_table('mapping_rules')
    op.drop_index(op.f('ix_contracts_workspace_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_name'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_counterparty_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_budget_items_id'), table_name='budget_items')
    op.drop_table('budget_items')
    op.drop_index(op.f('ix_planned_payments_payment_date'), table_name='planned_payments')
    op.drop_table('planned_payments')
    op.drop_index(op.f('ix_dds_articles_name'), table_name='dds_articles')
    op.drop_index(op.f('ix_dds_articles_id'), table_name='dds_articles')
    op.drop_table('dds_articles')
    op.drop_index(op.f('ix_counterparties_name'), table_name='counterparties')
    op.drop_index(op.f('ix_counterparties_id'), table_name='counterparties')
    op.drop_table('counterparties')
    op.drop_index(op.f('ix_budgets_id'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_index(op.f('ix_accounts_name'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_workspaces_name'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_id'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_account_types_id'), table_name='account_types')
    op.drop_table('account_types')
    # ### end Alembic commands ###