"""Add composite unique constraint to dds_articles

Revision ID: 181cba90f6ab
Revises: 1560c173c94b
Create Date: 2025-07-04 14:26:48.333347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '181cba90f6ab'
down_revision: Union[str, None] = '1560c173c94b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_dds_article_name_workspace_uc', 'dds_articles', ['name', 'workspace_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_dds_article_name_workspace_uc', 'dds_articles', type_='unique')
    # ### end Alembic commands ###
