"""Add is_income to dds_articles

Revision ID: 221b99b594d3
Revises: b6c41f7dd32c
Create Date: 2025-06-20 15:47:05.123456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '221b99b594d3'
down_revision = 'b6c41f7dd32c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dds_articles', schema=None) as batch_op:
        # 1. Добавляем колонку как nullable=True (временно)
        batch_op.add_column(sa.Column('is_income', sa.Boolean(), nullable=True)) # <--- ИЗМЕНЕНО: nullable=True

    # 2. Обновляем существующие записи, чтобы установить значение по умолчанию
    # Это делается вне batch_alter_table, напрямую через SQLAlchemy
    op.execute("UPDATE dds_articles SET is_income = FALSE WHERE is_income IS NULL") # <--- ДОБАВЛЕНО

    with op.batch_alter_table('dds_articles', schema=None) as batch_op:
        # 3. Изменяем колонку, чтобы она стала NOT NULL
        batch_op.alter_column('is_income',
                              existing_type=sa.Boolean(),
                              nullable=False) # <--- ДОБАВЛЕНО: Теперь nullable=False

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dds_articles', schema=None) as batch_op:
        batch_op.drop_column('is_income')

    # ### end Alembic commands ###