"""Add dds_article_id to transactions table

Revision ID: 256d63e564c6
Revises: 510901c9d431
Create Date: 2025-07-04 13:45:58.622938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '256d63e564c6'
down_revision: Union[str, None] = '510901c9d431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_dds_article_name_workspace_uc', 'dds_articles', type_='unique')
    # op.drop_index('ix_dds_articles_name', table_name='dds_articles')
    # op.create_index(op.f('ix_dds_articles_name'), 'dds_articles', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dds_articles_name'), table_name='dds_articles')
    op.create_index('ix_dds_articles_name', 'dds_articles', ['name'], unique=False)
    op.create_unique_constraint('_dds_article_name_workspace_uc', 'dds_articles', ['name', 'workspace_id'])
    # ### end Alembic commands ###
