"""Change dds_articles name uniqueness to per-workspace

Revision ID: 2daf8e87d37d
Revises: 72917ad01d48
Create Date: 2025-07-04 10:47:37.812014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2daf8e87d37d'
down_revision: Union[str, None] = '72917ad01d48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dds_articles_name', table_name='dds_articles')
    op.create_index(op.f('ix_dds_articles_name'), 'dds_articles', ['name'], unique=False)
    op.create_unique_constraint('_dds_article_name_workspace_uc', 'dds_articles', ['name', 'workspace_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_dds_article_name_workspace_uc', 'dds_articles', type_='unique')
    op.drop_index(op.f('ix_dds_articles_name'), table_name='dds_articles')
    op.create_index('ix_dds_articles_name', 'dds_articles', ['name'], unique=True)
    # ### end Alembic commands ###
