"""Adjust type column in BudgetItem model

Revision ID: 3133436557dc
Revises: 9c5c6f7691bf
Create Date: 2025-07-08 11:02:18.143738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3133436557dc'
down_revision: Union[str, None] = '9c5c6f7691bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_items', sa.Column('type', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budget_items', 'type')
    # ### end Alembic commands ###
