"""add_counterparty_fk_to_transactions

Revision ID: 3947553c11ed
Revises: a7d58c334940
Create Date: 2025-07-09 17:30:51.734745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3947553c11ed'
down_revision: Union[str, None] = 'a7d58c334940'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_counterparties_id'), 'counterparties', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_counterparties_id'), table_name='counterparties')
    # ### end Alembic commands ###
