"""add_counterparties_table

Revision ID: 4259d4c80669
Revises: 41c208ec8da8
Create Date: 2025-07-09 15:59:48.472853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4259d4c80669'
down_revision: Union[str, None] = '41c208ec8da8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_planned_payments_payment_date', table_name='planned_payments')
    op.drop_table('planned_payments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planned_payments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Описание платежа'),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False, comment='Сумма платежа (всегда положительная)'),
    sa.Column('payment_date', sa.DATE(), autoincrement=False, nullable=False, comment='Планируемая дата'),
    sa.Column('payment_type', postgresql.ENUM('INCOME', 'EXPENSE', name='paymenttype'), autoincrement=False, nullable=False, comment='Тип: доход или расход'),
    sa.Column('is_recurring', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('recurrence_rule', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Правило повторения (напр., RRULE)'),
    sa.Column('workspace_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='planned_payments_owner_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name='planned_payments_workspace_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='planned_payments_pkey')
    )
    op.create_index('ix_planned_payments_payment_date', 'planned_payments', ['payment_date'], unique=False)
    # ### end Alembic commands ###
