# /backend/alembic/versions/4259d4c80669_add_counterparties_table.py

"""add_counterparties_table

Revision ID: 4259d4c80669
Revises: 41c208ec8da8
Create Date: 2025-07-09 11:30:00.123456 

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '4259d4c80669'
down_revision: Union[str, None] = '41c208ec8da8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counterparties',
        # ... (здесь все ваши столбцы для таблицы counterparties)
    )
    # op.drop_index('ix_planned_payments_payment_date', table_name='planned_payments') # <-- УДАЛИТЕ ИЛИ ЗАКОММЕНТИРУЙТЕ ЭТУ СТРОКУ
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index('ix_planned_payments_payment_date', 'planned_payments', ['payment_date'], unique=False) # <-- И ЭТУ ТОЖЕ
    op.drop_table('counterparties')
    # ### end Alembic commands ###