"""Adjust type column in BudgetItem model

Revision ID: 5c5ac05394c4
Revises: 3133436557dc
Create Date: 2025-07-08 11:05:40.534123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c5ac05394c4'
down_revision: Union[str, None] = '3133436557dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
