"""Add active_workspace_id to User model

Revision ID: 6cb13333af45
Revises: fe25dd9285fe
Create Date: 2025-06-21 23:08:02.162898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cb13333af45'
down_revision: Union[str, None] = 'fe25dd9285fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_workspace_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_active_workspace_id'), ['active_workspace_id'], unique=False)
        batch_op.create_foreign_key(None, 'workspaces', ['active_workspace_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_active_workspace_id'))
        batch_op.drop_column('active_workspace_id')

    # ### end Alembic commands ###
