"""Add workspace_id to dds_articles table

Revision ID: 72917ad01d48
Revises: 5f1f0f0e7e86
Create Date: 2025-07-04 10:40:04.452176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72917ad01d48'
down_revision: Union[str, None] = '5f1f0f0e7e86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dds_articles', sa.Column('workspace_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'dds_articles', 'workspaces', ['workspace_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dds_articles', type_='foreignkey')
    op.drop_column('dds_articles', 'workspace_id')
    # ### end Alembic commands ###
