"""Remove type column from BudgetItem

Revision ID: 72969885258b
Revises: 5c5ac05394c4
Create Date: 2025-07-08 11:08:56.294883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72969885258b'
down_revision: Union[str, None] = '5c5ac05394c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budget_items', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_items', sa.Column('type', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
