"""Remove type column from BudgetItem

Revision ID: 9c5c6f7691bf
Revises: e6bca8f8ddb7
Create Date: 2025-07-08 10:30:37.761716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c5c6f7691bf'
down_revision: Union[str, None] = 'e6bca8f8ddb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budget_items', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_items', sa.Column('type', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
