"""Add Contract model and update Transaction/Counterparty links

Revision ID: a55bafe1f12a
Revises: <NEW_REVISION_ID_ЗДЕСЬ>
Create Date: 2025-07-10 19:49:31.080444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a55bafe1f12a'
down_revision: Union[str, None] = '<NEW_REVISION_ID_ЗДЕСЬ>'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment='Название договора/проекта'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание договора/проекта'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='Дата начала договора'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='Дата окончания договора'),
    sa.Column('value', sa.Float(), nullable=True, comment='Сумма договора'),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'ARCHIVED', 'PENDING', name='contractstatus'), nullable=False, comment='Статус договора'),
    sa.Column('counterparty_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_counterparty_id'), 'contracts', ['counterparty_id'], unique=False)
    op.create_index(op.f('ix_contracts_id'), 'contracts', ['id'], unique=False)
    op.create_index(op.f('ix_contracts_name'), 'contracts', ['name'], unique=False)
    op.create_index(op.f('ix_contracts_workspace_id'), 'contracts', ['workspace_id'], unique=False)
    op.add_column('transactions', sa.Column('contract_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_transactions_contract_id'), 'transactions', ['contract_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'contracts', ['contract_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_contract_id'), table_name='transactions')
    op.drop_column('transactions', 'contract_id')
    op.drop_index(op.f('ix_contracts_workspace_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_name'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_counterparty_id'), table_name='contracts')
    op.drop_table('contracts')
    # ### end Alembic commands ###
