"""add_counterparty_fk_to_transactions

Revision ID: a7d58c334940
Revises: 4259d4c80669
Create Date: 2025-07-09 17:15:33.591786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7d58c334940'
down_revision: Union[str, None] = '4259d4c80669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # УДАЛЕНА НЕПРАВИЛЬНАЯ КОМАНДА: op.drop_table('planned_payments')
    op.add_column('transactions', sa.Column('counterparty_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_transactions_counterparty_id'), 'transactions', ['counterparty_id'], unique=False)
    # Имя внешнего ключа добавлено для совместимости
    op.create_foreign_key('fk_transactions_counterparty_id', 'transactions', 'counterparties', ['counterparty_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # УДАЛЕНА НЕПРАВИЛЬНАЯ КОМАНДА: op.create_table(...)
    op.drop_constraint('fk_transactions_counterparty_id', 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_counterparty_id'), table_name='transactions')
    op.drop_column('transactions', 'counterparty_id')
    # ### end Alembic commands ###