"""Add is_superuser column to users table

Revision ID: afc5d0c01c3f
Revises: 9ad51e95d1c5
Create Date: 2025-06-18 15:37:11.141644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afc5d0c01c3f'
down_revision: Union[str, None] = '9ad51e95d1c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
