"""Add missing currency column to workspaces

Revision ID: b5d52f4efb13
Revises: cd532ba335c3
Create Date: 2025-06-18 16:13:45.234616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5d52f4efb13'
down_revision: Union[str, None] = 'cd532ba335c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
