"""Add code column to dds_articles table

Revision ID: b6c41f7dd32c
Revises: 950f1b84b192
Create Date: 2025-06-19 22:35:41.083896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6c41f7dd32c'
down_revision: Union[str, None] = '950f1b84b192'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dds_articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_dds_articles_code'), ['code'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dds_articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dds_articles_code'))
        batch_op.drop_column('code')

    # ### end Alembic commands ###
