"""fix null is_superuser values in users table

Revision ID: c3368000f61c
Revises: afc5d0c01c3f
Create Date: 2024-05-18 19:42:04.593259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3368000f61c'
down_revision: Union[str, None] = 'afc5d0c01c3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Команда ниже вызывала ошибку, так как колонка 'is_superuser' еще не существовала.
    # Мы комментируем ее, так как при создании новой базы она не нужна.
    # op.execute("UPDATE users SET is_superuser = FALSE WHERE is_superuser IS NULL")
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Так как мы ничего не делали в upgrade, в downgrade тоже ничего делать не нужно.
    pass
    # ### end Alembic commands ###