"""Add missing columns to workspace and other tables

Revision ID: cd532ba335c3
Revises: afc5d0c01c3f
Create Date: 2025-06-18 16:12:33.483712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd532ba335c3'
down_revision: Union[str, None] = 'afc5d0c01c3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
