"""Make from_account_id in transactions nullable

Revision ID: cf5471620d83
Revises: 181cba90f6ab
Create Date: 2025-07-04 21:42:44.422928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf5471620d83'
down_revision: Union[str, None] = '181cba90f6ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'from_account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'from_account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
