"""Add items relationship to Budget model

Revision ID: e6bca8f8ddb7
Revises: 3de0b4d0e657
Create Date: 2025-07-08 09:52:01.336067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6bca8f8ddb7'
down_revision: Union[str, None] = '3de0b4d0e657'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
