"""Remove is_income column from dds_articles

Revision ID: f62ff93a4572
Revises: 4d559058ac14
Create Date: 2025-06-21 13:51:02.855621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f62ff93a4572'
down_revision: Union[str, None] = '4d559058ac14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dds_articles', schema=None) as batch_op:
        batch_op.drop_column('is_income')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dds_articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_income', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
