"""Add MappingRule model for automatic transaction categorization

Revision ID: fe25dd9285fe
Revises: f62ff93a4572
Create Date: 2025-06-21 20:36:49.391668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe25dd9285fe'
down_revision: Union[str, None] = 'f62ff93a4572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
